name: Actualizar Datos ETH

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  actualizar_datos:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Configurar flujo de trabajo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 2. Configurar Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: 3. Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Ejecutar script de recolección (Collector)
        run: |
          python src/proyecto/static/models/collector.py

      - name: 5. Ejecutar script de enriquecimiento (Enricher)
        run: |
          python src/enricher.py

      - name: 6. Ejecutar script de modelado (Modeller)
        run: |
          python src/proyecto/static/models/modeller.py

      - name: 7. Ejecutar script de la aplicación (App)
        run: |
          python src/proyecto/static/models/app.py

      - name: 8. Ejecutar script del dashboard (Dashboard)
        run: |
          python src/proyecto/static/models/dashboard.py

      - name: 9. Listamos archivos y directorios
        run: ls -lR

      - name: 10. Commit y subir cambios
        run: |
          git --version
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add src/proyecto/static/data/historical.db \
                    src/proyecto/static/data/historical.csv \
                    src/proyecto/static/data/enriched_historical.db \
                    src/proyecto/static/models/collector.log \
                    src/proyecto/static/models/arima_model.pkl
          git commit -m "Actualizar datos económicos y ejecutar pipelines" || echo "No hay cambios para commitear"
          git push origin main

      - name: 11. Trabajo completado
        run: echo "Todos los cambios y script se ejecutaron. Flujo de trabajo finalizado."
